name: Build LaTeX document

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
      
    permissions:
      contents: write

    steps:
      
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: '0'

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
        with:
          prefix: 'v'

      - name: Show the next version
        run: |
          echo ${{ steps.get_next_version.outputs.version }}
          echo ${{ steps.get_next_version.outputs.hasNextVersion }}

      - name: Update version.tex, tag, commit, push
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        env:
          NEW_VERSION: ${{ steps.get_next_version.outputs.version }}
        shell: bash
        run: |
          old_version=$(git describe --tags --abbrev=0)
          sed -i "s/$old_version/$NEW_VERSION/" version.tex
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add version.tex
          git commit -m "Bump version $old_version->${{ steps.get_next_version.outputs.version }}"
          git push
                    
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.1.0
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        with:
          root_file: main.tex

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.get_next_version.outputs.version }}
          tag_name: ${{ steps.get_next_version.outputs.version }}
          draft: false
          prerelease: false
          files: main.pdf

